name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Firefox extension
        run: npm run build firefox
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          
      - name: Build Chrome extension
        run: npm run build chrome
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/firefox/*.zip
            dist/chrome/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 